Repository CS2103-AY1819S1-F10-3/main, pull requests merged in 2018-11, with the labels that each got.

#206 Populate table with service provider results
  docs/images/Ui.png
  src/main/java/seedu/address/commons/events/ui/DisplayAutoMatchResultRequestEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ServiceCard.java
  src/main/java/seedu/address/ui/ServiceListPanel.java
  src/main/resources/view/ServiceListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/ServiceCardHandle.java
  src/test/java/guitests/guihandles/ServiceListPanelHandle.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/ui/ClientServiceCardTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High

#213 Bump app version
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, status.Done

#214 Fix a bug where NullPointerException occurs when exiting the app
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Enhancement

#212 Fix select command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ClearBrowserPanelRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/DeselectRequestEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditPasswordCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/data/Account/accountlist.xml
  src/test/data/RegisterAccountCommandTest/accountlist_withrootonly.xml
  src/test/data/XmlAccountStorageTest/accountlist.xml
  src/test/data/XmlAccountStorageTest/accountlistToChangePassword.xml
  src/test/data/XmlUtilTest/accountlist.xml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/ui/ClientServiceCardTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ListCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
Labels: priority.High, status.Done

#211 Update UG to show both login and main screen UI
  docs/UserGuide.adoc
Labels: priority.High

#208 Add method to get contact details in URL
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Service.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High

#222 Fix automatch outputting contact type in logs
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
Labels: priority.Medium, severity.Low, status.Done, type.Bug

#231 Hide main window when login screen shown
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High

#237 Fix cost regex to reject symbols
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/model/contact/Service.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/contact/ServiceTest.java
Labels: priority.High, type.Bug

#238 Update my individual project portfolio
  docs/team/ganchinyao.adoc
  docs/team/images/AccountStorageClassDiagram.png
  docs/team/images/abouttheproject.png
  docs/team/images/accountcreationdiagram.png
  docs/team/images/accountstoragediagram.png
  docs/team/images/developerguideexample.png
  docs/team/images/developerguideheader.png
  docs/team/images/exampleimage.png
  docs/team/images/extract.png
  docs/team/images/intropicture.png
  docs/team/images/logotransparentbackground.png
  docs/team/images/major.png
  docs/team/images/minor.png
  docs/team/images/others.png
  docs/team/images/parta.png
  docs/team/images/partb.png
  docs/team/images/partc.png
  docs/team/images/projectportfolio.png
  docs/team/images/projectteam.png
  docs/team/images/quoteend.png
  docs/team/images/quotestart.png
  docs/team/images/userguideexample.png
  docs/team/images/userguideheader.png
Labels: priority.Low, type.Task

#241 Fix issue with presence of identifier in list and add not caught as error
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, severity.Medium, type.Bug

#240 Select contact on automatch
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
Labels: priority.Medium, status.Done, type.Enhancement

#252 Fix identifier bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AutoMatchCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
Labels: severity.High, type.Bug

#274 Fix wrong automatch messages
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Low, severity.Low, status.Done, type.Bug

#277 Deselect and clear list before automatching
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
Labels: priority.Low, severity.Low, status.Done, type.Bug

#280 Include service field in existing tests
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/storage/XmlAdaptedContact.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
  src/test/java/seedu/address/testutil/VendorBuilder.java
  src/test/java/seedu/address/ui/ClientServiceCardTest.java
Labels: priority.High

#283 Add enhancement to existing UG DG PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nightyeti.adoc
  src/main/java/seedu/address/storage/XmlAdaptedAccount.java
Labels: priority.Low, type.Enhancement

#284 Create AddServiceCommand tests
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddServiceCommandParser.java
  src/main/java/seedu/address/model/contact/Service.java
  src/test/java/seedu/address/logic/commands/AddServiceCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddServiceCommandParserTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/VendorBuilder.java
  src/test/java/systemtests/AddServiceCommandSystemTest.java
Labels: priority.High

#285 Update admin documents
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/eehooi.adoc
  docs/team/ngeehooi.adoc
Labels: priority.Medium

#279 Replace quotes with backticks for undo and redo in UG
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, type.Enhancement

#292 Change name
  docs/team/wailunlim.adoc
Labels: type.Epic

#289 Small fixes and changes to UG
  docs/UserGuide.adoc
Labels: priority.Low, severity.Low, status.Done, type.Enhancement

#290 Add icons for tips, notes and danger
  docs/UserGuide.adoc
  docs/images/icon-danger.png
  docs/images/icon-notes.png
  docs/images/icon-tips.png
Labels: priority.Low, severity.Low, status.Done, type.Enhancement

#291 Add tests for auto-matching
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/logic/parser/AutoMatchCommandParser.java
  src/main/java/seedu/address/model/ContactType.java
  src/test/java/seedu/address/logic/commands/AutoMatchCommandTest.java
  src/test/java/seedu/address/logic/parser/AutoMatchCommandParserTest.java
  src/test/java/seedu/address/model/ContactTypeTest.java
Labels: priority.Medium, status.Done, type.Enhancement

#226 Add some content to project portfolio
  docs/DeveloperGuide.adoc
  docs/images/auto-matching.png
  docs/team/images/auto-matching.png
  docs/team/images/automatching.png
  docs/team/images/icon-danger.png
  docs/team/images/icon-notes.png
  docs/team/images/icon-tips.png
  docs/team/images/screenshot.png
  docs/team/liaujianjie.adoc
Labels: priority.Low, severity.Low, status.Ongoing, type.Enhancement

#297 Show user's role at bottom center of screen
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/account/Role.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
Labels: priority.Medium, type.Enhancement

#296 Change app logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/heart2_logo_transparent.png
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#301 Create default data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.High

#299 Update documentations, client/vendor same name bug fix
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ListAllClients.png
  docs/images/ListClientsWithKeywords.png
  docs/images/Ui.png
  docs/images/UiLoginDiagram.png
  docs/images/callouts2.png
  docs/stylesheets/gh-pages.css
  docs/stylesheets/style.css
  docs/team/nightyeti.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/resources/view/LoginWindow.fxml
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: priority.Medium, type.Enhancement

#307 Fix a bug in update command causing entire data to disappear
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
Labels: priority.High, severity.High, type.Bug

#308 Change limwailun -> wailunlim
  docs/AboutUs.adoc
Labels: type.Epic

#311 Update parts of UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Medium

#312 Update DG
  docs/DeveloperGuide.adoc
  docs/images/DeleteClientSdForLogic.png
  docs/images/DeletePersonSdForLogic.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/SdForDeleteClient.png
  docs/images/SdForDeleteClientEventHandling.png
  src/main/java/seedu/address/model/contact/UniqueContactList.java
Labels: type.Enhancement

#315 Update DG appendix
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.Medium

#318 Update project portfolio for myself
  docs/team/wailunlim.adoc
Labels: type.Epic

#316 Change current UG callouts to the default callouts
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Low, type.Enhancement

#319 Fix the bug where logging out and logging in can undo states
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#320 Remove unused test cases
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/ClientListPanelTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Low, type.Enhancement

#322 Update PPP to reflect changes in UG
  docs/team/nightyeti.adoc
Labels: type.Enhancement

#323 Update AddService Implementation for UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddServiceSequenceDiagram.pptx
  docs/images/AddServiceSequenceDiagram.png
Labels: priority.Medium

#324 Update PPP
  docs/team/eehooi.adoc
Labels: priority.Medium

#327 Remove delete manual testing and fix minor PPP details
  docs/DeveloperGuide.adoc
  docs/team/eehooi.adoc
Labels: priority.Medium

#330 Disallow sensitive commands from storing parameters to history
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
Labels: priority.Medium, type.Enhancement

#336 Update DG to tell user how to change default root account credentials
  docs/DeveloperGuide.adoc
  docs/team/nightyeti.adoc
  src/main/java/seedu/address/model/account/Account.java
Labels: priority.Low, type.Enhancement
