Repository CS2103-AY1819S1-F10-3/main, pull requests merged in 2018-10, with the labels that each got.

#101 Update login UI to prepare for pre-main launch
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/LoginWindow.fxml
Labels: priority.Medium

#103 Remove previous developer photos
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
Labels: priority.Low

#109 Add to Developer Guide: Implementation
  docs/DeveloperGuide.adoc
  docs/images/accountcreationdiagram.png
  docs/images/accountstoragediagram.png
Labels: priority.Low, type.Enhancement

#110 DG: Update Login and Search Result Implementation
  docs/DeveloperGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiClassDiagram.png
  docs/images/UiLoginDiagram.png
Labels: priority.Low, status.Done

#88 Implement matchmake
  src/main/java/seedu/address/logic/commands/MatchMakeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchMakeCommandParser.java
Labels: priority.High, status.Done, type.Enhancement

#117 Add documentation for matchmaking to developer guide
  docs/DeveloperGuide.adoc
  docs/images/matchmaking.png
Labels: priority.Low, status.Done

#121 Add test case for XmlAdaptedAccount class
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/storage/XmlAdaptedAccount.java
  src/test/java/seedu/address/storage/XmlAdaptedAccountTest.java
  src/test/java/seedu/address/testutil/TypicalAccount.java
Labels: priority.Medium, type.Task

#123 Add junit test for XmlAccountStorage class
  src/main/java/seedu/address/storage/XmlAccountStorage.java
  src/test/data/XmlAccountStorageTest/InvalidAndValidUsernameAccountList.xml
  src/test/data/XmlAccountStorageTest/InvalidUsernameAccountList.xml
  src/test/data/XmlAccountStorageTest/NotXmlFormatAccountList.xml
  src/test/data/XmlAccountStorageTest/accountlist.xml
  src/test/java/seedu/address/storage/XmlAccountStorageTest.java
  src/test/java/seedu/address/testutil/TypicalAccount.java
Labels: priority.Medium, type.Task

#124 Add junit test for XmlSerializableAccountList class
  src/main/java/seedu/address/model/account/AccountList.java
  src/test/data/XmlSerializableAccountListTest/duplicateAccount_AccountList.xml
  src/test/data/XmlSerializableAccountListTest/invalidAccount_AccountList.xml
  src/test/data/XmlSerializableAccountListTest/typicalAccount_AccountList.xml
  src/test/java/seedu/address/storage/XmlSerializableAccountListTest.java
  src/test/java/seedu/address/testutil/TypicalAccount.java
Labels: priority.Medium, type.Task

#125 Add junit test for AccountList class
  src/test/java/seedu/address/model/account/AccountListTest.java
  src/test/java/seedu/address/testutil/TypicalAccount.java
Labels: priority.Medium, type.Task

#126 Add junit test for Account class and Role enum
  src/main/java/seedu/address/model/account/Account.java
  src/test/java/seedu/address/model/account/AccountTest.java
  src/test/java/seedu/address/model/account/RoleTest.java
Labels: priority.Medium, type.Task

#111 Update app name and version in documentation
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.Low, status.Ongoing

#127 Add junit test for LoginCommand and RegisterAccountCommand
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/RegisterAccountCommand.java
  src/main/java/seedu/address/logic/security/AccountManager.java
  src/main/java/seedu/address/storage/XmlAccountStorage.java
  src/test/data/LoginCommandTest/accountlist_withrootonly.xml
  src/test/data/LoginCommandTest/accountlist_withselfregisteredaccount.xml
  src/test/data/RegisterAccountCommandTest/accountlist_withrootonly.xml
  src/test/data/RegisterAccountCommandTest/invalidaccountlist_wrongstructure.xml
  src/test/data/RegisterAccountCommandTest/notevenxmlstructure.xml
  src/test/data/SystemTest/rootaccount_accountlist.xml
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterAccountCommandTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAccountStorageTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ListCommandSystemTest.java
  src/test/java/systemtests/LoginHelper.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, type.Task

#145 Beautify developer guide
  docs/DeveloperGuide.adoc
  docs/images/appendixaheader.png
  docs/images/appendixbheader.png
  docs/images/appendixcheader.png
  docs/images/appendixdheader.png
  docs/images/appendixeheader.png
  docs/images/appendixfheader.png
  docs/images/appendixgheader.png
  docs/images/appendixhheader.png
  docs/images/calloutpic.png
  docs/images/designheader.png
  docs/images/devopsheader.png
  docs/images/documentationheader.png
  docs/images/guidefordevelopers.png
  docs/images/implementationheader.png
  docs/images/settingup.png
  docs/images/testingheader.png
Labels: priority.Low, type.Enhancement

#148 Activate LoginWindow
  docs/images/UiLoginDiagram.png
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/LoginWindow.fxml
  src/test/java/seedu/address/TestApp.java
Labels: priority.Medium

#144 Update Client Summary Table UI panel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ServiceListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ic_catering.png
  src/main/resources/images/ic_dress.png
  src/main/resources/images/ic_hotel.png
  src/main/resources/images/ic_invitation.png
  src/main/resources/images/ic_photographer.png
  src/main/resources/images/ic_ring.png
  src/main/resources/images/ic_transport.png
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ServiceListPanel.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: priority.High, status.Ongoing

#143 Fix XML serialization and deserialzation for client and service provider
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/tempAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedClientTest.java
  src/test/java/seedu/address/ui/ClientListPanelTest.java
Labels: priority.High, severity.High, status.Done, type.Bug

#162 Update Client Summary Table UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ServiceListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ic_catering.png
  src/main/resources/images/ic_dress.png
  src/main/resources/images/ic_hotel.png
  src/main/resources/images/ic_invitation.png
  src/main/resources/images/ic_photographer.png
  src/main/resources/images/ic_ring.png
  src/main/resources/images/ic_transport.png
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ServiceListPanel.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: priority.Medium, severity.Medium

#154 Hide main window details before login
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LoginWindow.fxml
Labels: priority.Low, status.Ongoing, type.Enhancement

#163 Fix login error message
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/resources/view/LoginWindow.fxml
Labels: priority.Medium

#165 Add EditPasswordCommand and LogoutCommand
  src/main/java/seedu/address/commons/util/XmlUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditPasswordCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/RegisterAccountCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPasswordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/model/account/AccountList.java
  src/main/java/seedu/address/storage/AccountStorage.java
  src/main/java/seedu/address/storage/XmlAccountStorage.java
  src/test/data/Account/accountlist.xml
  src/test/data/XmlAccountStorageTest/accountlistToChangePassword.xml
  src/test/data/XmlUtilTest/accountlist.xml
  src/test/data/XmlUtilTest/accountlistEmptyPassword.xml
  src/test/data/XmlUtilTest/accountlistEmptyRole.xml
  src/test/data/XmlUtilTest/accountlistEmptyUsername.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/parser/EditPasswordCommandParserTest.java
  src/test/java/seedu/address/model/account/AccountListTest.java
  src/test/java/seedu/address/storage/XmlAccountStorageTest.java
Labels: priority.Medium, type.Task

#170 Update name of edit command class
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/storage/XmlAccountStorage.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
Labels: priority.Low, status.Done

#173 Add salt and hash to Account password
  src/main/java/seedu/address/commons/util/XmlUtil.java
  src/main/java/seedu/address/logic/commands/EditPasswordCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/RegisterAccountCommand.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/RegisterAccountCommandParser.java
  src/main/java/seedu/address/logic/security/PasswordAuthentication.java
  src/main/java/seedu/address/model/account/Account.java
  src/main/java/seedu/address/model/account/AccountList.java
  src/main/java/seedu/address/storage/AccountStorage.java
  src/main/java/seedu/address/storage/XmlAccountStorage.java
  src/test/data/Account/accountlist.xml
  src/test/data/LoginCommandTest/accountlist_withrootonly.xml
  src/test/data/LoginCommandTest/accountlist_withselfregisteredaccount.xml
  src/test/data/RegisterAccountCommandTest/accountlist_withrootonly.xml
  src/test/data/RegisterAccountCommandTest/invalidaccountlist_wrongstructure.xml
  src/test/data/SystemTest/rootaccount_accountlist.xml
  src/test/data/XmlAccountStorageTest/InvalidAndValidUsernameAccountList.xml
  src/test/data/XmlAccountStorageTest/InvalidUsernameAccountList.xml
  src/test/data/XmlAccountStorageTest/accountlist.xml
  src/test/data/XmlAccountStorageTest/accountlistToChangePassword.xml
  src/test/data/XmlSerializableAccountListTest/duplicateAccount_AccountList.xml
  src/test/data/XmlSerializableAccountListTest/invalidAccount_AccountList.xml
  src/test/data/XmlSerializableAccountListTest/typicalAccount_AccountList.xml
  src/test/data/XmlUtilTest/accountlist.xml
  src/test/data/XmlUtilTest/accountlistEmptyPassword.xml
  src/test/data/XmlUtilTest/accountlistEmptyRole.xml
  src/test/data/XmlUtilTest/accountlistEmptyUsername.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/EditPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RegisterAccountCommandParserTest.java
  src/test/java/seedu/address/logic/security/PasswordAuthenticationTest.java
  src/test/java/seedu/address/model/account/AccountListTest.java
  src/test/java/seedu/address/model/account/AccountTest.java
  src/test/java/seedu/address/storage/XmlAccountStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableAccountListTest.java
  src/test/java/seedu/address/testutil/PasswordUtil.java
  src/test/java/seedu/address/testutil/TypicalAccount.java
Labels: priority.Medium, type.Task

#174 Create Add Service command
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddServiceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Service.java
  src/main/java/seedu/address/model/serviceprovider/ServiceProvider.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedService.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ServiceProviderBuilder.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, status.Ongoing

#178 Fix a bug when adding contacts
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug

#185 Update UG for Add service command
  docs/UserGuide.adoc
Labels: priority.Medium

#186 Update Service class to incorporate id list
  src/main/java/seedu/address/model/contact/Service.java
Labels: priority.Medium

#187 Update user guide to reflect the updated commands
  docs/UserGuide.adoc
  docs/images/userguide.png
  docs/images/userguideimage.png
  src/main/java/seedu/address/logic/commands/EditPasswordCommand.java
  src/main/java/seedu/address/logic/commands/RegisterAccountCommand.java
Labels: priority.Low, type.Enhancement

#195 Implement client matchmaking
  src/main/java/seedu/address/logic/commands/MatchMakeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/contact/Service.java
Labels: priority.High, status.Ongoing, type.Enhancement

#190 Update developer guide to make it relevant
  docs/DeveloperGuide.adoc
  docs/images/AccountStorageClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.Low, type.Enhancement

#202 Conform to string uniformity for Add Service command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddServiceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Low, status.Done

#205 Update ModelManager with AutoMatch results
  src/main/java/seedu/address/logic/commands/AutoMatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AutoMatchResult.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, status.Done, type.Enhancement
